### ISSUE TITLE
Beginning the changelog

### ISSUE THREAD

**Issue by ExpHP** [lloydmeta/frunk#120]
I like @Centril's idea of following https://keepachangelog.com/en/1.0.0/

Note: To follow it 100%, there are a good 38 versions that need to be retroactively documented; that seems like a pretty big chore!  I'm tempted to say to just start at 0.2.0 with a list of everything frunk currently has to offer.

**Comment by Centril** [comment]
Oh; I didn't know that you're supposed to document all versions 😄.

I super agree that we should start with 0.2.0 ;)

**Comment by lloydmeta** [comment]
Agreed. Definitely let's start with 0.2.0 😆

**Comment by Centril** [comment]
Btw... does starting with 0.2.0 mean that the changelog should include all the things that are in 0.2.0 or just that versions > 0.2.0 are documented in the changelog?

**Comment by ExpHP** [comment]
> include all the things that are in 0.2.0 

this one.  It's what the example on the keepachangelog page does.  You can also see [rust did it here](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-01--2012-01-20)

**Comment by ExpHP** [comment]
By the way, I'm not sure how to handle the separate subcrates.  (since there will be times when not all of them need a version bump)

---

(I just went to go see what num does: [they haven't kept good track either](https://github.com/rust-num/num/blob/master/RELEASES.md) :stuck_out_tongue: )

**Comment by ExpHP** [comment]
We could also just plop down a stub changelog so that we at least have an `[Unreleased]` section that we can update for now

**Comment by Centril** [comment]
@ExpHP Ah; Since you did most of the work on 0.2.0, would you like to take charge of writing the changelog?

Wrt. the subcrates, I think that if we only bump a single subcrate, then it makes sense to say which subcrate the release is for. Otherwise, it is probably best to talk about them as one monolithic frunk. It should hopefully be clear from the documentation which crate things applies to, and we also have re-exports.

👍 on Unreleased for now.

**Comment by ExpHP** [comment]
Closed by #121
