### ISSUE TITLE
Macro to call `h_cons()` repeatedly

### ISSUE THREAD

**Issue by abonander** [lloydmeta/frunk#58]
It seems like this should be pretty simple to implement, just something like this should do:

```rust
macro_rules! h_cons (
    ($hlist:expr; $($cons:expr),+) => {
        {
            let hlist = $hlist;
            $(let hlist = h_cons($cons, hlist);)+
            hlist
         }
    }
);
```

**Comment by lloydmeta** [comment]
Hi there,

This sounds interesting :) Can you please share a use-case for something like this?

**Comment by abonander** [comment]
To complete [this answer](https://www.reddit.com/r/rust/comments/6gq5gg/hey_rustaceans_got_an_easy_question_ask_here/div11vz/), it would be used to add the last few fields to the intermediate `HList`, so something like:

```rust
let fields = into_labelled_generic(config_toml);
let fields = h_cons!(fields; field!(..), field!(..), field!(..));
let config: ServerConfig = from_labelled_generic(fields);
```

**Comment by abonander** [comment]
Also, is there a reason why `field!()` needs a `ty` kind for its first argument? I think `ident` would work fine there, then you wouldn't need strawman enums everywhere.

**Comment by lloydmeta** [comment]
Thanks for the use-case. Thinking about it again, the proposed macro looks like it does something similar to [simply concatenating 2 Hlists](https://github.com/lloydmeta/frunk/blob/master/core/src/hlist.rs#L936-L942) (which IMO is a bit more intuitive in the way it handles ordering):

```rust
hlist![1,2,3] + existing_hlist;
```

> Also, is there a reason why `field!()` needs a `ty` kind for its first argument?

That argument is used as the type parameter to the `labelled::field_with_name` method, so I thought a type argument would make sense. If we relax it to `ident` then yes, we could generate a hidden enum.

It might be worth exploring adding such an overload (passing `ident` generates an enum?) , but it might make it too easy for people to accidentally write non-portable `Field`s. By non-portable `Field`, I mean that it can't really be used with things like `#[derive(LabelledGeneric)]`, since the `Field`'s type might refer to an enum that's declared within a function, or module.

**Comment by abonander** [comment]
I didn't realize you could concat hlists, but I see the `Add` impl now. I guess I can go back and update my answer then, cool.

**Comment by lloydmeta** [comment]
I'll close this issue for now. Feel free to re-open if needed.
